default_vs_type: milvus
milvus:
  uri: Your_URI
  user: Your_User
  password: Your_Password
kb_name: VulnBotModel
chunk_size: 750
overlap_size: 150
top_n: 1
top_k: 3
score_threshold: 0.5
search_params:
  top_n: 10
  score_threshold: 0.8
  search_method: IVF_FLAT
  index_params:
    nlist: 1000
    metric_type: COSINE
index_params:
  metric_type: COSINE
  index_type: HNSW
  params:
    M: 16
    efConstruction: 200
text_splitter_dict:
  SpacyTextSplitter:
    source: huggingface
    tokenizer_name_or_path: gpt2
  RecursiveCharacterTextSplitter:
    source: tiktoken
    tokenizer_name_or_path: cl100k_base
text_splitter_name: RecursiveCharacterTextSplitter
