api_key: 
  YOUR_API_KEY_HERE
llm_model: openai
base_url: https://api.openai.com/v1
llm_model_name: gpt-4o-mini
embedding_models: maidalun1020/bce-embedding-base_v1
embedding_type: local
context_length: 120000
embedding_url: ''
rerank_model: maidalun1020/bce-reranker-base_v1
temperature: 0.5
history_len: 5
timeout: 600
proxies: {}
